service: wetrace-api
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
functions:
  postLocation:
    handler: handler.postLocation
    events:
      - http:
          path: /location
          method: post
          integration: lambda-proxy
  postInfected:
    handler: handler.postInfected
    events:
      - http:
          path: /infected
          method: post
          integration: lambda-proxy
  getDevicesNearInfected:
    handler: handler.getDevicesNearInfected
    events:
      - http:
          path: /devices-near-infected
          method: get
          integration: lambda-proxy

vpc:
  securityGroupIds:
    - sg-03b5282aa8bd76a92
  subnetIds:
    - subnet-ff7dedb3
    - subnet-26ff0d4d
    - subnet-76153d0c

package:
  exclude:
    - "**/*"

  # include - we have to explicitly list packages with native dependencies.
  include:
    - "*.py"
    - "json"
    - "psycopg2-binary"

plugins:
  - serverless-python-requirements
